spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: funcionario
          uri: http://localhost:8092/funcionario
          predicates:
            - Path=/funcionario/**
        - id: sala
          uri: http://localhost:8091/sala
          predicates:
            - Path=/sala/**
        - id: agenda
          uri: http://localhost:8093/agenda
          predicates:
            - Path=/agenda/**
server:
  port: ${PORTA:8080}
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
